language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t philippdaun/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true philippdaun/react-test npm run test

after_success:
  - docker build -t philippdaun/docker-react-multi-nginx ./nginx
  - docker build -t philippdaun/docker-react-multi-client ./client
  - docker build -t philippdaun/docker-react-multi-server ./server
  - docker build -t philippdaun/docker-react-multi-worker ./worker
  # Log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push philippdaun/docker-react-multi-nginx
  - docker push philippdaun/docker-react-multi-client
  - docker push philippdaun/docker-react-multi-server
  - docker push philippdaun/docker-react-multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-013779734036
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
